AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation S3 bucket for CI/CD workflow'

Parameters:
  Environment:
    Type: String
    Default: 'test'
    AllowedValues:
      - test
      - staging
      - prod

Resources:
  MyS3CfnCicdBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-${Environment}-bucket'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: Github actions testing

Outputs:
  BucketName:
    Description: 'Name of created S3 bucket'
    Value: !Ref MyS3CfnCicdBucket